### ISSUE TITLE
Double quote string when non word character appears in string

### ISSUE THREAD

**Issue by take-cheeze** [mrbgems/mruby-yaml#21]
(Reported by @k0kubun san in [ruby-jp slack](https://ruby-jp.github.io) #mruby channel)

```ruby
yaml = 'foo:
- /bar
- /baz'
puts YAML.dump(YAML.load(yaml))
```

psych
```yaml
---
foo:
- "/bar"
- "/baz"
```

mruby
```
---
foo:
- /bar
- /baz
```

Psych seems to change the style of scalar depending on what's inside:
https://github.com/ruby/psych/blob/7bebf65e4d90a75b79057e50a89ca5af3f53500a/lib/psych/visitors/yaml_tree.rb#L277-L278

So we need to change the style like psych here:
https://github.com/mrbgems/mruby-yaml/blob/d925845dc3427925154bfc1fdbc35f0152fae743/src/yaml.c#L373

**Comment by k0kubun** [comment]
Roughly approached in https://github.com/mrbgems/mruby-yaml/commit/1fc78d05ea74411d794a9fbf7f32373fa0894d49
