### ISSUE TITLE
Numbers with underscores are converted to strings

### ISSUE THREAD

**Issue by kotovalexarian** [mrbgems/mruby-yaml#27]
I'm not sure if numbers with underscores are part of the standard, by **CRuby**'s **Psych** parser, which uses the same **libyaml**, understands them properly.

```yaml
// test.yml
foobar: 123_456_789
```

```ruby
# test.rb
p YAML.load(File.read('test.yml'))
# Expected: {"foobar"=>123456789}
# Got:      {"foobar"=>"123_456_789"}
```

I haven't run this example, maybe the test should be defined as a function and called from the interactive shell **mirb**. However the case takes place in a lot of tests of my project.

**Comment by k0kubun** [comment]
Fixed this in https://github.com/mrbgems/mruby-yaml/pull/28.
